services:
  web:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    environment:
      TZ: 'Asia/Tokyo'
      LANG: 'C.UTF-8'
      LC_ALL: 'C.UTF-8'
      APP_NAME: ${APP_NAME}
      APP_URL: ${APP_URL}

volumes:
  gemdata:
  bundle_data:
  node_modules:
